#!/bin/bash

ansible -u root --private-key /root/.ssh/id_rsa all -m user -a "name=automation"

ansible -u root --private-key /root/.ssh/id_rsa all -m authorized_key -a "user=automation state=present key={{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"

ansible -u root --private-key /root/.ssh/id_rsa all -m lineinfile -a "path=/etc/sudoers.d/automation line='automation ALL=(ALL) NOPASSWD: ALL' create=yes"
