---
- hosts: database
  tasks:
  - copy:
      content: 'dev,test,qa,prod'
      dest: /mnt/mysql_backups/database_list.txt
    become: yes

  - stat:
      path: /mnt/mysql_backups/database_list.txt
    register: dblist
    become: yes

  - archive:
      path: /mnt/mysql_backups/database_list.txt
      dest: /mnt/mysql_backups/archive.gz
      format: gz
    when: dblist.stat.exists
    become: yes
