---
- hosts: database
  tasks:
  - file:
      path: /etc/ansible/facts.d
      state: directory
      mode: '0755'
    become: yes
  - blockinfile:
      path: /etc/ansible/facts.d/custom.fact
      block: |
        [sample_exam]
        server_role=mysql
      create: yes
      owner: root
      group: root
      mode: '0644'
    become: yes
  - setup:
      filter: ansible_local
  - debug:
      var: ansible_local.custom.sample_exam
