---
- hosts: all
  tasks:
  - copy:
      content: 'Welcome to HAProxy server'
      dest: /etc/motd
    when: inventory_hostname in groups['proxy']
    become: yes

  - copy:
      content: 'Welcome to Apache server'
      dest: /etc/motd
    when: inventory_hostname in groups['webservers']
    become: yes

  - copy:
      content: 'Welcome to MySQL server'
      dest: /etc/motd
    when: inventory_hostname in groups['database']
    become: yes
