---
- hosts: all
  tasks:
  - yum:
      name:
      - tcpdump
      - mailx
      state: latest
    when: inventory_hostname in groups['proxy']
    become: yes
  - yum:
      name: 
      - lsof
      - mailx
      state: latest
    when: inventory_hostname in groups['database']
    become: yes
