---
- hosts: all
  tasks:
  - lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#Banner'
      line: Banner /etc/motd
    become: yes
    notify: restart sshd

  - lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^X11Forwarding'
      line: X11Forwarding no
    become: yes
    notify: restart sshd

  - lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^#MaxAuthTries'
      line: MaxAuthTries 3
    become: yes
    notify: restart sshd

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted
    become: yes
