---
- hosts: all
  vars_files:
  - /home/automation/plays/secret.yml
  - /home/automation/plays/vars/user_list.yml
  tasks:
  - user:
      name: "{{ item.username }}"
      password: "{{ user_password | password_hash('sha512') }}"
      uid: "{{ item.uid }}"
      groups: wheel
      append: yes
      shell: /bin/bash
      update_password: on_create
    loop: "{{ users }}"
    when: (item.uid is regex('^1.*') and inventory_hostname in groups['webservers']) or (item.uid is regex('^2.*') and inventory_hostname in groups['database'])
    become: yes
    notify: upload ssh key       

  handlers:
  - name: upload ssh key
    authorized_key:
      user: "{{ item.username }}"
      state: present
      key: "{{ lookup('file', '/home/automation/.ssh/id_rsa.pub') }}"
    loop: "{{ users }}"
    when: (item.uid is regex('^1.*') and inventory_hostname in groups['webservers']) or (item.uid is regex('^2.*') and inventory_hostname in groups['database'])
    become: yes
